export { default as ArrowIcon } from "./arrow-icon.svg"
export { default as ArrowRightIcon } from "./arrow-right-icon.svg"
export { default as BuildingsIcon } from "./buildings-icon.svg"
export { default as CalendarIcon } from "./calendar-icon.svg"
export { default as HomeIcon } from "./home-icon.svg"
export { default as ProfileIcon } from "./profile-icon.svg"
export { default as PublicationsIcon } from "./publications-icon.svg"
export { default as RoosterIcon } from "./rooster-icon.svg"
export { default as SearchIcon } from "./search-icon.svg"
export { default as TimeQuaterIcon } from "./time-quarter-icon.svg"
export { default as VerticalDotsIcon } from "./vertical-dots.svg"
export { default as Xicon } from "./x-icon.svg"

